// Korean readings of pinned source declarations, not present-day outcome claims.
export const narratives={
'metric-meta-program':['숫자만 있는 지표는 다음에 어떤 행동을 해야 하는지 설명하지 못합니다.','각 지표가 생산자·소비자·메타 연산을 명시하게 합니다.',{'metric-without-operation':['인디케이터에 메타 연산이 연결되지 않았습니다.','FAIL_CLOSED로 판정합니다.']}],
'executable-actionability':['권고가 있어도 실제로 실행할 방법이 없을 수 있습니다.','작업을 막는 인디케이터를 정해진 실행 도구에 연결합니다.',{'missing-executor':['차단 원인이 된 연산에 실행 도구가 없습니다.','FAIL_CLOSED로 판정합니다.']}],
'effect-bounded-observation':['분석 도구가 관측 대상 자체를 변경할 수 있습니다.','관측자에게 저장소 쓰기 0이라는 안전 제약을 둡니다.',{'observer-write':['증거 기록에 저장소 쓰기가 보고됩니다.','FAIL_CLOSED로 판정합니다.']}],
'monotone-semantic-resolution':['알 수 없는 의미가 성공인 것처럼 보일 수 있습니다.','정확한 연산을 주장할 수 없으면 불변 조건만 말하는 수준으로 해상도를 낮춥니다.',{'unknown-top-decision':['정확해야 하는 상위 판정값을 알 수 없습니다.','LOWER_RESOLUTION으로 판정합니다.']}],
'causal-feedback-chain':['초록색 산출물이라고 해서 현재 판단의 원인이 되는 증거인 것은 아닙니다.','유일하고 정확한 선행 산출물의 내용을 실행 가능한 의미 상태로 사용합니다.',{'ambiguous-rerun':['정규 선행 산출물이 두 개 존재합니다.','임의로 하나를 고르지 않고 FAIL_CLOSED로 판정합니다.']}],
'ci-selected-refactoring':['수동 정리가 검증 증거보다 앞서 진행될 수 있습니다.','CI 지표가 제한된 AST 변환을 선택하고 그 뒤 수용 여부를 판단합니다.',{'line-cap-debt':['CI가 212줄 평가기와 그 안의 89줄 사실 수집 함수를 관측하는 고정 사례입니다.','원문의 기대 결과는 파일 212→65줄, 파일 4개 생성, 재실행입니다. 현재 저장소 관측값은 아닙니다.']}],
'concept-governed-refactoring':['지표가 고른 연산에 의미론적 허용 근거가 없을 수 있습니다.','모든 후보 연산을 다이제스트를 통해 언어 개념에 연결합니다.',{'unregistered-strategy-operation':['전략이 개념에 연결되지 않은 연산을 지정합니다.','LOWER_RESOLUTION으로 판정합니다.']}],
'quantified-improvement':['정성적인 진전 표현이 바뀌지 않은 분모를 숨길 수 있습니다.','정확한 선행·현재 증거 기록으로 추정 없이 정수 변화량을 증명합니다.',{'one-obligation-gain':['비교 가능한 7/24와 8/24 기록 사이에 새 충족 항목 1개, 회귀 0개가 있습니다.','이 고정 사례의 기대 변화는 +1개, +417 BPS입니다.']}],
'verified-transformation-transaction':['제안이 통과해도 병합된 선행 증거가 없을 수 있습니다.','준비도를 올리기 전에 병합된 선행 기록을 선택하고 재실행합니다.',{'merged-dynamic-predecessor':['병합된 선행 기록이 정적 좌표 8개를 동적 입력 8개로 바꾸며, 알 수 없는 좌표와 쓰기는 0입니다.','정적 좌표 8→0, 동적 좌표 0→8, 해당 만분율 0→10,000이 기대됩니다.']}],
'autonomous-change-proposal':['생성된 제안이 병합 증거를 확보하기 전에 스스로 승인될 수 있습니다.','정확히 병합된 선행 제안을 선택하고 증명한 뒤에만 준비도에 반영합니다.',{'merged-proposal-predecessor':['정확한 병합 push 산출물 하나가 8/8 제안 계약을 만족하고 모호함·미해결 증거·쓰기·변경 권한이 모두 0입니다.','원문 사례의 기대값은 의무 충족 9/24→10/24와 +416 BPS입니다.']}],
'guarded-exact-promotion':['현재 승격 사건의 실패가 승격 능력 자체의 부재와 혼동될 수 있습니다.','허용된 기초 증거와 변경되지 않은 구현으로 능력을 증명하되 현재 사건의 실패를 다시 쓰지 않습니다.',{'event-failure-capability-proof':['최신 승격 사건은 FAIL_CLOSED지만 정확하게 승인된 구현은 바뀌지 않았습니다.','사건 실패를 보존하면서 사례의 준비도는 10/24→11/24, +417 BPS를 기대합니다.']}],
'rollback-fixed-point-recovery':['실패로 닫힌 승격 때문에 다음 선행 증거가 되어야 하는 workflow까지 실패 상태에 갇힐 수 있습니다.','무손실 스키마 투영과 효과 0의 변환으로 낮은 해상도를 권한을 부여하지 않는 고정점으로 회복합니다.',{'promotion-evidence-bootstrap-gap':['보호 조건은 해상도를 낮추고, 변환 기록은 효과 0과 변경되지 않은 소스 작업 공간을 증명합니다.','쓰기 0을 보존하면서 사례의 준비도 11/24→12/24, +417 BPS를 기대합니다.']}],
'toolchain-executable-use-cases':['문서화된 예제가 실패 경계를 실행하지 않고도 통과할 수 있습니다.','버전이 있는 레지스트리로 정상 1개와 실패로 닫혀야 하는 변형 2개를 재실행한 뒤 준비도에 반영합니다.',{'canonical-and-negative-replay':['정규 산출물 하나와 제한된 변형 두 개를 실행합니다.','3/3 사례와 원문 준비도 12/24→13/24가 기대됩니다.']}],
'language-syntax-roundtrip':['문법 예제가 존재해도 AST·바이트·의미·lens 보존을 증명한 것은 아닙니다.','버전이 있는 전체 사례 집합으로 결정론적 외부 보존 기록을 생성합니다.',{'complete-syntax-corpus-replay':['원문의 고정 사례는 완전한 소스 17개와 잘못된 입력 3개를 재실행하고 패키지 구성원 2개는 패키지 실행으로 보냅니다.','해당 사례의 기대는 20/20 통과와 준비도 13/24→14/24입니다. 현재 문법 사례 수로 사용하지 않습니다.']}],
'language-semantic-model':['문법 확장이 의미의 권한과 암묵적인 효과의 경계를 흐릴 수 있습니다.','정규화한 IR을 재실행해 의미·출처·증거·봉인된 효과를 분리합니다.',{'staged-semantic-authority-replay':['소스 13개, 권한 법칙 3개, 상위 입력 거절 2개를 재실행하는 원문 사례입니다.','18/18 사례, 효과 0과 준비도 14/24→15/24를 기대합니다.']}],
'language-deterministic-query':['질의가 암묵적인 절차에 불과하면 언어와 지표 연결을 재현 가능하게 조사할 수 없습니다.','질의 계획을 명시적이고 제한된 객체로 만들어 정규 기록을 반환하고, 후보 사실에는 권한을 부여하지 않습니다.',{'query-meta-bindings':['CI가 결정론적 질의 개념의 코드·지표 연결을 조사해야 합니다.','32/32 충족과 정규 재실행을 기대합니다.'],'replay-query-plan':['같은 명시적 질의 계획을 삽입 순서만 바뀐 메타 그래프에서 실행합니다.','요청·결과·그래프의 증거 기록이 모두 동일해야 합니다.'],'reject-query-unknowns':['질의가 알 수 없는 계층·끝점을 선택하거나 후보 사실만 관측합니다.','FAIL_CLOSED이며 권한 승격은 0이어야 합니다.']}],
'language-go-interoperation':['생성된 Go가 파싱돼도 공개 타입 경계·재실행 정체성·거절 권한은 증명되지 않을 수 있습니다.','순수한 메타 프로그램으로 기존 생성 결과를 Go AST와 타입으로 구체화하고 공개 API를 정규화하며 불명확하거나 암묵적인 경계를 거절합니다.',{'project-gooo-to-go-api':['CI가 고정 SemanticIR 입력 8개를 기존 생성기에 통과시킵니다.','소스 매핑과 API 재실행을 포함해 8/8 충족을 기대합니다.'],'consume-go-1.27-boundary':['Go 1.27로 제네릭 메서드·제네릭 별칭·대입 추론을 구체화합니다.','제네릭 메서드 5개와 별칭 2개를 포함한 8/8 충족을 기대합니다.'],'reject-go-boundary-unknowns':['유효하지 않은 경계, 암묵적 권한을 가져오는 경계, 공개 항목이 없는 경계, 알 수 없는 입력입니다.','8/8 거절과 잘못된 입력 수용 0을 기대합니다.']}],
'language-diagnostic-provenance':['진단에 오류 이름이 있어도 원인이 된 물리 바이트·논리 소스·의미 정체성은 증명되지 않을 수 있습니다.','읽기 전용 메타 프로그램이 포맷터·생성기·Go·LSP 증거를 재실행 가능한 출처 정보로 정규화하고 알 수 없는 부분의 해상도를 낮춥니다.',{'trace-generated-diagnostic':['생성된 Go 또는 포맷터 진단이 소스 맵 범위 하나에 들어갑니다.','4/4를 의미 ID와 LSP 범위로 추적하는 것을 기대합니다.'],'trace-line-directed-diagnostic':['Go가 보고한 생성 바이트의 //line 좌표가 물리 좌표와 다릅니다.','물리 좌표와 논리 좌표를 모두 보존해야 합니다.'],'reject-ambiguous-or-unknown-provenance':['기원·단계·심각도·좌표·소스 맵 증거 중 알 수 없는 항목이 있습니다.','8/8 거절과 해상도 하향을 기대합니다.']}],
'language-package-runtime':['파싱된 Gooo 파일들이 결정론적인 다중 패키지 실행 단위를 이루지 못할 수 있습니다.','고정 사례 집합으로 정규 패키지 초기화와 활동 계약 해석을 증명하도록 합니다.',{'deterministic-package-graph':['패키지 4개가 다이아몬드형 가져오기 그래프를 구성합니다.','정상 경로 10/10을 기대합니다.'],'multi-source-entry-contract':['Gooo 소스 2개와 진입 활동이 있습니다.','효과 0으로 진입점을 해석해야 합니다.'],'invalid-runtime-fail-closed':['잘못된 패키지 실행 경계 8개를 입력합니다.','8/8 거절을 기대합니다.']}],
'toolchain-cli':['명령이 존재해도 실행 종료·출력·재실행·효과 계약은 증명되지 않을 수 있습니다.','고정 메타 평가기로 빌드된 Gooo 바이너리를 결정론적 성공·거절 기록에 연결합니다.',{'inspect-cli-identity':['CI가 텍스트와 구조화된 버전 출력 계약을 호출합니다.','정체성 경로 2/2를 기대합니다.'],'execute-language-commands':['빌드된 바이너리로 문법·의미·왕복을 검사합니다.','언어 연산 4/4를 기대합니다.'],'reject-cli-boundaries':['누락되거나 알 수 없는 명령 경계 6개를 호출합니다.','쓰기 0으로 6/6 거절을 기대합니다.']}],
'toolchain-format-fix':['포맷과 수정이 버전 있는 의미 계획이나 고정점 증명 없이 파일을 변경할 수 있습니다.','하나의 빌드된 바이너리가 정규 소스와 읽기 전용 계획을 만들고, 메타 프로그램이 메모리에서 명시적인 고정점까지 적용합니다.',{'format-canonical-source':['CI가 텍스트·JSON·검사 모드를 호출합니다.','포맷 경로 3/3을 기대합니다.'],'plan-without-writing':['변경됨·고정점·텍스트 형식의 수정 계획을 관측합니다.','쓰기 0으로 수정 경로 3/3을 기대합니다.'],'reject-unknown-boundaries':['형식 오류·누락·미상·쓰기 권한 경로 6개를 호출합니다.','6/6 거절을 기대합니다.']}],
'toolchain-conformance':['개별 도구가 모두 통과해도 스키마·커밋 정체성·증거·효과 권한에 대해 서로 다를 수 있습니다.','버전 있는 메타 프로그램이 같은 head의 도구 기록 9개를 연결하고 메모리에서 제한된 불일치를 거절합니다.',{'same-head-surface-closure':['버전이 있는 도구 기록 9개를 CI가 결합합니다.','원문 계약은 9/9 영역과 152/152 사례를 기대합니다.'],'in-memory-drift-rejection':['CI가 기록에 제한된 변형 13개를 적용합니다.','13/13 FAIL_CLOSED를 기대합니다.'],'effect-authority-boundary':['기록에 쓰기 또는 변경 권한이 보고됩니다.','허용 경계는 쓰기 0·변경 권한 0입니다.']}],
'toolchain-lsp':['편집기 서버가 오래되거나 불확실한 의미 탐색을 정확한 언어 의미처럼 제공할 수 있습니다.','고정 실행 기록으로 파서의 정확한 상태를 투영하며, 의미 증거의 해상도가 낮아지면 탐색을 제공하지 않습니다.',{'editor-read-session':['CI가 고정된 표준 LSP 통신 기록을 재실행합니다.','프로토콜 사례 16/16을 기대합니다.'],'semantic-coupling-navigation':['정확한 의미 연결 설명 하나가 요청 위치를 포함합니다.','표준 LocationLink 하나를 기대합니다.'],'uncertain-coupling':['상위 의미가 미상·실패·오래됨·취소 상태입니다.','탐색 링크는 0개여야 합니다.']}],
'toolchain-cross-platform-release':['한 호스트에서 빌드가 성공한 것을 배포 가능한 언어 도구체인으로 오해할 수 있습니다.','고정된 네이티브 실행기 3개가 소스에 연결되고 재실행 결과가 같은 바이너리·보관 파일을 생성한 뒤 준비도에 반영합니다.',{'three-native-platforms':['고정 x64 실행기 3개에서 정확한 head를 빌드하고 실행합니다.','정확한 플랫폼 기록 3/3을 기대합니다.'],'reproducible-release-candidate':['각 실행기가 CLI를 두 번 빌드하고 패키징합니다.','바이너리 빌드 6회와 보관 파일 빌드 6회의 바이트 동일성을 기대합니다.'],'uncertain-platform-receipt':['기록이 누락·중복·오래됨 상태이거나 판정값이 미상입니다.','준비도를 인정하지 않고 FAIL_CLOSED로 판정합니다.']}],
'language-delivery-scorecard':['내부 준비도를 사용자가 느끼는 언어 완전성과 혼동할 수 있습니다.','고정 전달 계약으로 같은 증거 집합을 독자별 해상도에서 보여주고 알려진 누락을 보존합니다.',{'known-delivery-gaps':['고정 의무 5개에 실행 가능한 기록이 없습니다.','INCOMPLETE 31/36을 기대합니다.'],'reader-resolution':['사용자·도구 제작자·관리자가 같은 사실을 봅니다.','원문 사례는 각각 9/12·19/24·31/36으로 표시합니다. 서로 다른 분모를 합산하지 않습니다.'],'unknown-source-receipt':['상위 판정이 명시적인 PASS가 아닙니다.','FAIL_CLOSED와 해상도 하향을 기대합니다.']}],
'language-source-execution':['활동 계약이 파싱돼도 사용자가 실행할 수 있는 언어 상태 전이가 없을 수 있습니다.','Gooo가 자기 온톨로지의 전이를 실행하고 결정론적이며 실패를 숨기지 않는 기록을 생성하도록 합니다.',{'execute-billing':['사용자가 선언된 PayOrder 활동을 선택합니다.','소스 실행 1회·이벤트 4개의 PASS를 기대합니다.'],'deterministic-replay':['같은 소스와 진입점을 두 번 실행합니다.','정확한 바이트 재현 1/1을 기대합니다.'],'unknown-entry':['선택한 활동이 없습니다.','FAIL_CLOSED / SOURCE_ENTRY_UNKNOWN을 기대합니다.']}],
'language-ci-plan-usecase':['언어가 내부 증명만 쌓고 사용자가 볼 수 있는 개발 작업은 닫지 못할 수 있습니다.','Gooo 메타 프로그램이 변경 파일을 제한적이고 결정론적인 CI 계획, 정확히 위치한 미상 원인, 자원 현황으로 바꿉니다.',{'changed-files-to-ci-receipt':['사용자가 변경된 저장소 경로를 PlanCI 활동에 입력합니다.','쓰기 0을 보존하며 PASS 4개·FAIL_CLOSED 4개·원인이 위치로 표현된 UNKNOWN 4개를 재실행하는 것이 원문의 기대입니다.']}]
};
const oracle=['생성자가 스스로 검증하면 결정론적 산출물도 의미상 소스에 연결되지 않을 수 있습니다.','의존성이 분리된 판정기가 제한된 Gooo 소스 의미를 투영하고 다이제스트가 유효한 위조도 거절합니다.',{'genuine-source-bound':['실제 실행 산출물을 원시 Gooo 소스와 비교합니다.','정확한 소스 연결 1/1의 PASS를 기대합니다.'],'resealed-output-forgery':['실행 후 출력 엔티티를 바꿨지만 다이제스트 형식은 유효합니다.','FAIL_CLOSED / ARTIFACT_SOURCE_PROJECTION_MISMATCH를 기대합니다.'],'unknown-artifact-decision':['다이제스트가 유효한 산출물에 알 수 없는 판정값이 있습니다.','FAIL_CLOSED / ARTIFACT_DECISION_UNKNOWN을 기대합니다.'],'unsupported-source-projection':['소스가 판정기의 고정 문법 범위를 벗어납니다.','판정기 파싱 단계에서 FAIL_CLOSED와 해상도 하향을 기대합니다.']}];
narratives['language-artifact-oracle']=oracle;
narratives['language-source-binding-promotion']=oracle;
