import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {concepts,translateMetric} from './translations.mjs';
const [input,template,output]=process.argv.slice(2);
const raw=await readFile(input,'utf8');
const atlas=JSON.parse(raw);
if(atlas.schema!=='gooo/source-metric-atlas/v1'||!Array.isArray(atlas.concepts)||!Array.isArray(atlas.obligations)||!Array.isArray(atlas.metrics))throw Error('Unsupported source catalog');
for(const concept of atlas.concepts){concept.translation=concepts[concept.id]?{title:concepts[concept.id][0],description:concepts[concept.id][1],state:'EDITORIAL'}:{title:concept.id,description:'한국어 해설 미작성. 원문을 유지합니다.',state:'MISSING'};}
for(const metric of atlas.metrics)metric.translation=translateMetric(metric.id);
for(const metric of atlas.metrics)metric.source_contracts=(atlas.source_contracts?.calls??[]).filter(call=>call.metric_id===metric.id);
atlas.catalog_sha256=createHash('sha256').update(raw).digest('hex');
atlas.presentation_scope='REGISTRY_EXPORT_AND_LITERAL_INDEX_NOT_CURRENT_CONFORMANCE';
const json=JSON.stringify(atlas).replaceAll('<','\\u003c');
const html=await readFile(template,'utf8');
const marker='<script id="atlas-data" type="application/json">null</script>';
if(!html.includes(marker))throw Error('Atlas template marker absent');
await writeFile(output,html.replace(marker,()=>`<script id="atlas-data" type="application/json">${json}</script>`));
const report={source_sha:atlas.source_sha,concepts:atlas.concepts.length,obligations:atlas.obligations.length,assurance_obligations:atlas.assurance_obligations.length,metric_ids_and_candidates:atlas.metrics.length,lexical_activity_declarations:atlas.activities.length,scanned_files:atlas.scanned_sources.length,excluded_files:atlas.excluded_paths.length,concept_translations_missing:atlas.concepts.filter(c=>c.translation.state==='MISSING').map(c=>c.id),metric_labels_with_untranslated_tokens:atlas.metrics.filter(m=>m.translation.untranslated_tokens.length).length,current_conformance:'UNASSESSED'};
await writeFile(output+'.receipt.json',JSON.stringify(report,null,2)+'\n');
if(process.env.GITHUB_STEP_SUMMARY)await writeFile(process.env.GITHUB_STEP_SUMMARY,'## Source metric atlas\n\n```json\n'+JSON.stringify(report,null,2)+'\n```\n');
console.log(JSON.stringify(report));
