import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {concepts,translateMetric,metricTranslationCatalog,untranslatedCohortIds} from './translations.mjs';
import {narratives} from './narratives-ko.mjs';
import {annotateFields,observedFieldVocabulary} from './source-field-guide.mjs';
import {nativeEvidence,bindNativeEvidence} from './native-evidence.mjs';
import {validateReleaseMetricBindings} from './release-metric-validator.mjs';
import {validateSourceReferences} from './source-reference-validation.mjs';
const [input,template,output,sourceRoot]=process.argv.slice(2);
if(!sourceRoot)throw Error('sourceRoot is required for source-backed rendering');
function metricTraceability(metric,translation){
  const sourceBacked=translation.source_backed;
  if(sourceBacked)return {identifier:metric.id,identifier_kind:sourceBacked.identifier_kind,original_label:metric.id,rendered_label:translation.ko,untranslated_tokens:translation.untranslated_tokens,source:metric.references??[],callsites:(metric.source_contracts??[]).map(contract=>({metric_id:contract.metric_id,package_scope:contract.package_scope,path:contract.call.path,line:contract.call.line,kind:contract.call.kind,helper:contract.helper})),classification:sourceBacked.classification,meaning_status:sourceBacked.semantic_state,explanation:sourceBacked.explanation,source_evidence:sourceBacked.source_evidence,unknown:sourceBacked.unknown,failure_stage:sourceBacked.unknown?.stage??null,failure_reason:sourceBacked.unknown?.reason??null,next_operation:sourceBacked.unknown?.next_operation??null};
  const references=metric.references??[];
  const contracts=metric.source_contracts??[];
  const candidate=references.some(reference=>reference.kind==='literal_call_candidate_not_global_identity');
  const classification=contracts.length?'GLOSSARY_TOKEN_MISSING':candidate?'CANDIDATE_ID_UNCONFIRMED':'SOURCE_MEANING_OR_ID_UNCONFIRMED';
  const failure=contracts.length?{stage:'TRANSLATION_GLOSSARY',reason:'TOKEN_NOT_IN_EDITORIAL_DICTIONARY;SOURCE_CONTRACT_SYMBOLIC_ONLY',next_operation:'REVIEW_GLOSSARY_TOKEN_AGAINST_SOURCE_CONTRACT'}:candidate?{stage:'SOURCE_IDENTITY',reason:'LOCAL_OR_LITERAL_CANDIDATE_NOT_GLOBAL_IDENTITY',next_operation:'CONFIRM_GLOBAL_METRIC_ID_AND_SEMANTICS'}:{stage:'SOURCE_IDENTITY',reason:'NO_FORMAL_SOURCE_CONTRACT_OR_RUNTIME_SEMANTIC_EVIDENCE',next_operation:'CONFIRM_REGISTRY_OR_CONSTRUCTOR_BINDING'};
  return {identifier:metric.id,identifier_kind:contracts.length?'SOURCE_METRIC_ID':candidate?'CANDIDATE':'UNCONFIRMED_METRIC_ID',original_label:metric.id,rendered_label:translation.ko,untranslated_tokens:translation.untranslated_tokens,source:references,callsites:contracts.map(contract=>({metric_id:contract.metric_id,package_scope:contract.package_scope,path:contract.call.path,line:contract.call.line,kind:contract.call.kind,helper:contract.helper})),classification,meaning_status:contracts.length?'SOURCE_CONTRACT_SYMBOLIC_NOT_RUNTIME_PROOF':candidate?'CANDIDATE_ID_UNCONFIRMED':'SOURCE_MEANING_OR_ID_UNCONFIRMED',failure_stage:failure.stage,failure_reason:failure.reason,next_operation:failure.next_operation};
}
function traceabilityRecords(metrics){return metrics.flatMap(metric=>metric.translation?.traceability?[metric.translation.traceability]:[]);}
function countTraceabilityClasses(records){return Object.fromEntries([...new Set(records.map(record=>record.classification))].sort().map(classification=>[classification,records.filter(record=>record.classification===classification).length]));}
function assertTraceabilityPartition(){const sample=[{translation:{traceability:null}},{translation:{traceability:{classification:'GLOSSARY_TOKEN_MISSING'}}},{translation:{traceability:{classification:'SOURCE_MEANING_OR_ID_UNCONFIRMED'}}}];const records=traceabilityRecords(sample);const counts=countTraceabilityClasses(records);if(records.length!==2||counts.GLOSSARY_TOKEN_MISSING!==1||counts.SOURCE_MEANING_OR_ID_UNCONFIRMED!==1||Object.values(counts).reduce((sum,count)=>sum+count,0)!==records.length)throw Error('Traceability population partition regression');}
function sourceDefinitionKey(call){return JSON.stringify({helper:call.helper,helper_signature:call.helper_signature,result_field_expressions:call.result_field_expressions});}
function sourceDefinitionBinding(metric,calls){
  const identifierKind=metricTranslationCatalog[metric.id]?.identifier_kind;
  const dynamicPrefix=identifierKind==='DYNAMIC_METRIC_PREFIX';
  const candidate=identifierKind==='CODE_LOCATION_CANDIDATE'||identifierKind==='CANDIDATE'||(metric.references??[]).some(reference=>reference.kind==='literal_call_candidate_not_global_identity');
  const definitionCount=new Set(calls.map(sourceDefinitionKey)).size;
  let state='NO_EXACT_SOURCE_CONTRACT';
  let reason='이 행의 ID와 정확히 같은 source constructor contract callsite가 없습니다.';
  let nextOperation='CONFIRM_GLOBAL_METRIC_ID_AND_SOURCE_DEFINITION';
  if(calls.length){
    state=definitionCount>1?'SOURCE_BOUND_MULTIPLE_DEFINITIONS':calls.length>1?'SOURCE_BOUND_MULTIPLE_CALLSITES':'SOURCE_BOUND';
    reason=definitionCount>1?'같은 ID에 서로 다른 source helper 정의가 있어 모든 callsite를 분리 보존합니다.':calls.length>1?'같은 ID의 여러 source callsite를 하나의 runtime 값으로 합치지 않습니다.':'정확히 일치하는 source metric ID의 constructor contract를 연결했습니다.';
    nextOperation='NONE_FOR_SOURCE_DEFINITION_JOIN';
  }else if(dynamicPrefix){
    state='DYNAMIC_PREFIX_NOT_CONFIRMED';
    reason='source가 생성된 metric prefix만 노출하므로 완전한 단일 ID나 constructor definition으로 승격하지 않습니다.';
    nextOperation='RESOLVE_GENERATED_METRIC_ID_FROM_SOURCE_DECLARATION';
  }else if(candidate){
    state='CANDIDATE_ID_NOT_CONFIRMED';
    reason='literal 또는 code-location 후보는 전역 metric ID와 source definition으로 승격하지 않습니다.';
    nextOperation='CONFIRM_GLOBAL_METRIC_ID_AND_SOURCE_DEFINITION';
  }
  return {schema:'gooo/source-definition-binding/v1',binding_scope:'SOURCE_DEFINITION_ONLY_NOT_RUNTIME_EVIDENCE',source_contract_property:'metric.source_contracts',state,metric_id:metric.id,exact_metric_id:calls.length?metric.id:null,callsite_count:calls.length,definition_count:definitionCount,definition_grouping:'helper/signature/result shape; not semantic or runtime-value equivalence',reason,next_operation:nextOperation};
}
const typedSourcePolicyFiles={vocabulary:'internal/meta/sourcepolicy/vocabulary_part02.go',indicator:'internal/meta/sourcepolicy/evaluate_part01.go',dispatch:'internal/meta/sourcepolicy/evaluate_part02.go',action:'internal/meta/generation/action.go',identity:'internal/meta/generation/canonical_part01.go',transformation:'internal/meta/transformationeffect/input.go',coverage:'internal/meta/artifactcoverage/bindings.go'};
const typedSourcePolicySpecs=[
  {metric_id:'gooo.metric.source.go-file-lines.v1',constant:'DimensionGoFileLines',meaning_ko:'Go 파일별 줄 수를 다루는 source-policy 차원',target_ko:'원본 producer가 보고한 Go 파일의 줄 수 관측',scope_ko:'report.Files에서 Go 파일의 file.Lines로 관측되며 전체 저장소 줄 수로 일반화하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value/limit 비교만 선언되어 단위는 미확정입니다.',conditions:['driverCapDefinition(FamilyVolume, policy.MaxFileLines, OperationSplitGo, "source-splitter")'],comparison:'RelationLessOrEqual · policy.MaxFileLines',role:'DRIVER',consumer:'source-splitter',operation:'OperationSplitGo',dispatch_anchor:'case DimensionGoFileLines:',helper_anchor:'func driverCapDefinition('},
  {metric_id:'gooo.metric.source.gooo-file-lines.v1',constant:'DimensionGoooFileLines',meaning_ko:'Gooo 파일별 줄 수를 다루는 source-policy 차원',target_ko:'원본 producer가 보고한 Gooo 파일의 줄 수 관측',scope_ko:'report.Files에서 Gooo 파일의 file.Lines로 관측되며 전체 저장소 줄 수로 일반화하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value/limit 비교만 선언되어 단위는 미확정입니다.',conditions:['driverCapDefinition(FamilyVolume, policy.MaxFileLines, OperationSplitGooo, "source-splitter")'],comparison:'RelationLessOrEqual · policy.MaxFileLines',role:'DRIVER',consumer:'source-splitter',operation:'OperationSplitGooo',dispatch_anchor:'case DimensionGoooFileLines:',helper_anchor:'func driverCapDefinition('},
  {metric_id:'gooo.metric.source.function-lines.v1',constant:'DimensionFunctionLines',meaning_ko:'함수 줄 수를 다루는 source-policy 차원',target_ko:'원본 Analyze가 실제로 보고한 finding.Actual',scope_ko:'Analyze의 Findings에 나타난 finding.Actual만 보존하며 전체 함수 전부의 관측으로 넓히지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value/limit 비교만 선언되어 단위는 미확정입니다.',conditions:['driverCapDefinition(FamilyVolume, policy.MaxFunctionLines, OperationExtractFunction, "function-extractor")'],comparison:'RelationLessOrEqual · policy.MaxFunctionLines',role:'DRIVER',consumer:'function-extractor',operation:'OperationExtractFunction',dispatch_anchor:'case DimensionFunctionLines:',helper_anchor:'func driverCapDefinition('},
  {metric_id:'gooo.metric.source.go-files.v1',constant:'DimensionGoFiles',meaning_ko:'Go 파일 개수를 관찰하는 source-policy 차원',target_ko:'원본 producer가 보고한 Go 파일 개수',scope_ko:'producer가 보고한 파일 집합에 한정하며 저장소 전체의 파일 의미나 성공을 추론하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위는 미확정입니다.',conditions:['case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:'},
  {metric_id:'gooo.metric.source.gooo-files.v1',constant:'DimensionGoooFiles',meaning_ko:'Gooo 파일 개수를 관찰하는 source-policy 차원',target_ko:'원본 producer가 보고한 Gooo 파일 개수',scope_ko:'producer가 보고한 파일 집합에 한정하며 저장소 전체의 파일 의미나 성공을 추론하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위는 미확정입니다.',conditions:['case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:'},
  {metric_id:'gooo.metric.source.go-lines.v1',constant:'DimensionGoLines',meaning_ko:'Go 줄 수 합계를 관찰하는 source-policy 차원',target_ko:'원본 producer가 report.Total로 보고한 Go 줄 수 집계',scope_ko:'producer가 보고한 report.Total 집계에 한정하며 저장소 전체 줄 수로 확장하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위는 미확정입니다.',conditions:['case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:'},
  {metric_id:'gooo.metric.source.gooo-lines.v1',constant:'DimensionGoooLines',meaning_ko:'Gooo 줄 수 합계를 관찰하는 source-policy 차원',target_ko:'원본 producer가 report.Total로 보고한 Gooo 줄 수 집계',scope_ko:'producer가 보고한 report.Total 집계에 한정하며 저장소 전체 줄 수로 확장하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위는 미확정입니다.',conditions:['case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionGoFiles, DimensionGoooFiles, DimensionGoLines, DimensionGoooLines:'},
  {metric_id:'gooo.metric.layout.direct-files.v1',constant:'DimensionDirectFiles',meaning_ko:'직접 파일 항목 수를 관찰하는 source-policy 차원',target_ko:'원본 topology producer가 보고한 직접 파일 항목 수',scope_ko:'관찰된 directory 범위의 직접 파일 항목에 한정하며 파일 내용·확장자 종류의 의미로 바꾸지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위는 미확정입니다.',conditions:['case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:','observe.family = FamilyTopology','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:'},
  {metric_id:'gooo.metric.layout.direct-folders.v1',constant:'DimensionDirectFolders',meaning_ko:'직접 하위 폴더 항목 수를 관찰하는 source-policy 차원',target_ko:'원본 topology producer가 보고한 직접 하위 폴더 항목 수',scope_ko:'관찰된 directory 범위의 직접 하위 폴더 항목에 한정하며 폴더 이름의 의미로 바꾸지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위은 미확정입니다.',conditions:['case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:','observe.family = FamilyTopology','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:'},
  {metric_id:'gooo.metric.layout.recursive-files.v1',constant:'DimensionRecursiveFiles',meaning_ko:'재귀 파일 항목 수를 관찰하는 source-policy 차원',target_ko:'원본 topology producer가 보고한 재귀 파일 항목 수',scope_ko:'관찰된 directory 아래의 재귀 파일 항목에 한정하며 파일 내용·확장자 종류의 의미로 바꾸지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위는 미확정입니다.',conditions:['case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:','observe.family = FamilyTopology','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:'},
  {metric_id:'gooo.metric.layout.recursive-folders.v1',constant:'DimensionRecursiveFolders',meaning_ko:'재귀 하위 폴더 항목 수를 관찰하는 source-policy 차원',target_ko:'원본 topology producer가 보고한 재귀 하위 폴더 항목 수',scope_ko:'관찰된 directory 아래의 재귀 하위 폴더 항목에 한정하며 폴더 이름의 의미로 바꾸지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value만 다루므로 단위는 미확정입니다.',conditions:['case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:','observe.family = FamilyTopology','return observe'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-report',operation:'OperationObserve',dispatch_anchor:'case DimensionDirectFiles, DimensionDirectFolders, DimensionRecursiveFiles, DimensionRecursiveFolders:'},
  {metric_id:'gooo.metric.layout.direct-entries.v1',constant:'DimensionDirectEntries',meaning_ko:'직접 파일과 직접 하위 폴더를 합친 항목 수를 다루는 source-policy 차원',target_ko:'원본 topology producer의 DirectFiles + DirectFolders',scope_ko:'직접 파일과 직접 하위 폴더의 합으로만 관찰하며 DirectoryKinds와 혼동하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value/limit 비교만 선언되어 단위는 미확정입니다.',conditions:['policy.ExemptProjectRootTopology && observation.Subject == "."','policy.MaxDirectDirectoryIn == 0','policy.MaxDirectDirectoryIn != 0'],comparison:'RelationObserve 또는 RelationLessOrEqual · policy.MaxDirectDirectoryIn',role:'UNSPECIFIED_IN_SOURCE',consumer:'repository-projector 또는 metric-report',operation:'OperationExemptRoot 또는 OperationObserve 또는 OperationPartition',dispatch_anchor:'case DimensionDirectEntries:'},
  {metric_id:'gooo.metric.layout.entry-kinds.v1',constant:'DimensionDirectoryKinds',meaning_ko:'직접 파일과 직접 하위 폴더의 존재 종류 수를 다루는 source-policy 차원',target_ko:'원본 topology producer의 int(DirectFiles > 0) + int(DirectFolders > 0)',scope_ko:'값은 0/1/2이며 직접 파일과 하위 폴더의 존재 종류 수·혼재만 뜻합니다. 진입점 종류나 Go/Gooo 확장자 종류가 아닙니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 Value/limit 비교만 선언되어 단위는 미확정입니다.',conditions:['policy.ExemptProjectRootTopology && observation.Subject == "."','!policy.RequireHomogeneousDirectories','policy.RequireHomogeneousDirectories'],comparison:'RelationObserve 또는 RelationLessOrEqual · limit 1',role:'UNSPECIFIED_IN_SOURCE',consumer:'repository-projector 또는 metric-report',operation:'OperationExemptRoot 또는 OperationObserve 또는 OperationSeparateKinds',dispatch_anchor:'case DimensionDirectoryKinds:'},
  {metric_id:'gooo.metric.documentation.root-readme-presence.v1',constant:'DimensionRootREADME',meaning_ko:'프로젝트 루트 README 존재를 다루는 source-policy 차원',target_ko:'rootREADMEObservation이 요구하는 프로젝트 루트 대상',scope_ko:'observation.Subject가 "."인 경우만 허용되며 root README producer가 보고한 관측을 일반 문서 품질로 확장하지 않습니다.',unit_ko:'원본 정의는 limit 1 또는 관찰 관계를 사용하지만 Unit 필드는 선언하지 않습니다.',conditions:['observation.Subject != "."이면 오류','policy.ExemptProjectRootREADME','!policy.ExemptProjectRootREADME'],comparison:'RelationObserve 또는 RelationEqual · limit 1',role:'UNSPECIFIED_IN_SOURCE',consumer:'metric-meta-program 또는 repository-documenter',operation:'OperationExemptRootREADME 또는 OperationRequireRootREADME',dispatch_anchor:'if observation.Dimension == DimensionRootREADME {',subject_expression:'observation.Subject == "."'},
  {metric_id:'gooo.metric.refactor.duplicate-body.v1',constant:'DimensionRefactorDuplicate',meaning_ko:'중복 본문을 다루는 source-policy 차원',target_ko:'duplicates.Analyze가 실제로 보고한 중복 finding',scope_ko:'중복 분석기가 보고한 finding에 한정하며 저장소의 모든 함수가 중복 없음을 뜻하지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 limit 0 비교만 선언되어 단위는 미확정입니다.',conditions:['capDefinition(FamilyDuplication, 0, OperationExtractFunction, "deduplicator")'],comparison:'RelationLessOrEqual · limit 0',role:'UNSPECIFIED_IN_SOURCE',consumer:'deduplicator',operation:'OperationExtractFunction',dispatch_anchor:'case DimensionRefactorDuplicate:'},
  {metric_id:'gooo.metric.refactor.single-return.v1',constant:'DimensionRefactorReturn',meaning_ko:'single-return finding을 관찰하는 source-policy 차원',target_ko:'Analyze가 실제로 보고한 single-return finding.Actual',scope_ko:'Analyze의 Findings에 나타난 finding.Actual만 보존하며 전체 함수 전부의 관측이라고 넓히지 않습니다.',unit_ko:'원본 source-policy 파일에는 Unit 필드가 없고 관찰 관계만 선언되어 단위는 미확정입니다.',conditions:['definition{family: FamilyRefactor, relation: RelationObserve, blocking: false, proof: ProofCoherence, operation: OperationInspectWrapper, consumer: "refactor-report"}'],comparison:'RelationObserve',role:'UNSPECIFIED_IN_SOURCE',consumer:'refactor-report',operation:'OperationInspectWrapper',dispatch_anchor:'case DimensionRefactorReturn:'},
  {metric_id:'gooo.metric.refactor.assign-return.v1',constant:'DimensionRefactorAssign',meaning_ko:'assign-return 후보를 다루는 source-policy 차원',target_ko:'Analyze가 실제로 보고한 assign-return finding.Actual',scope_ko:'Analyze의 Findings에 나타난 finding.Actual만 보존합니다. candidateDefinition 본문 밖의 조건·단위·consumer는 미확정입니다.',unit_ko:'candidateDefinition 호출만 확인되며 Unit은 미확정입니다.',conditions:['candidateDefinition(OperationCollapseAssign)'],comparison:'candidateDefinition 본문 미확정',role:'미확정',consumer:'미확정',operation:'OperationCollapseAssign',dispatch_anchor:'case DimensionRefactorAssign:'},
  {metric_id:'gooo.metric.conformance.go-fix-delta.v1',constant:'DimensionFixDelta',meaning_ko:'go-fix 변화량을 다루는 source-policy 차원',target_ko:'이 source-policy 파일이 요구하는 go-fix 변화량 관측',scope_ko:'이 함수는 FixDelta/Toolchain 관측을 만들지 않으므로 producer의 수집 범위를 이 파일만으로 넓히지 않습니다.',unit_ko:'원본 정의는 limit 0 비교를 사용하지만 Unit 필드는 선언하지 않습니다.',conditions:['definition{family: FamilyConformance, limit: 0, relation: RelationLessOrEqual, blocking: true, proof: ProofCoherence, operation: OperationModernize, consumer: "go-fix"}'],comparison:'RelationLessOrEqual · limit 0',role:'UNSPECIFIED_IN_SOURCE',consumer:'go-fix',operation:'OperationModernize',dispatch_anchor:'case DimensionFixDelta:'},
  {metric_id:'gooo.metric.conformance.toolchain.v1',constant:'DimensionToolchain',meaning_ko:'toolchain 적합성 선택을 다루는 source-policy 차원',target_ko:'이 source-policy가 선택하는 toolchain 관측',scope_ko:'이 함수는 Toolchain 관측을 만들지 않으므로 producer의 수집 범위를 이 파일만으로 넓히지 않습니다.',unit_ko:'원본 정의는 limit 1 비교를 사용하지만 Unit 필드는 선언하지 않습니다.',conditions:['definition{family: FamilyConformance, limit: 1, relation: RelationEqual, blocking: true, proof: ProofRegression, operation: OperationSelectToolchain, consumer: "go-toolchain-selector"}'],comparison:'RelationEqual · limit 1',role:'UNSPECIFIED_IN_SOURCE',consumer:'go-toolchain-selector',operation:'OperationSelectToolchain',dispatch_anchor:'case DimensionToolchain:'}
];
function uniqueSourceLine(text,needle,path){const lines=text.split(/\r?\n/);const matches=[];for(const [index,line] of lines.entries())if(line.includes(needle))matches.push(index+1);if(matches.length!==1)throw Error('Expected one source anchor for '+path+' '+needle+'; got '+matches.length);return matches[0];}
function sourceReference(path,line,symbol,kind){return {path,line,symbol,kind};}
async function buildTypedSourcePolicy(sourceRoot,sourceSHA){
  const sourceText={};
  for(const path of Object.values(typedSourcePolicyFiles))sourceText[path]=await readFile(`${sourceRoot}/${path}`,'utf8');
  const dimensions=[];
  const dimensionPattern=/^\s*(Dimension[A-Za-z0-9]+)\s+Dimension\s*=\s*"([^"]+)"/gm;
  for(const match of sourceText[typedSourcePolicyFiles.vocabulary].matchAll(dimensionPattern))dimensions.push({constant:match[1],metric_id:match[2]});
  if(dimensions.length!==19||new Set(dimensions.map(entry=>entry.metric_id)).size!==19)throw Error('Pinned source-policy dimension vocabulary is not exactly 19 unique IDs');
  const dimensionByConstant=new Map(dimensions.map(entry=>[entry.constant,entry]));
  if(typedSourcePolicySpecs.length!==19||typedSourcePolicySpecs.some(spec=>dimensionByConstant.get(spec.constant)?.metric_id!==spec.metric_id))throw Error('Typed source-policy specification does not match pinned Dimension vocabulary');
  const indicatorText=sourceText[typedSourcePolicyFiles.indicator],dispatchText=sourceText[typedSourcePolicyFiles.dispatch],actionText=sourceText[typedSourcePolicyFiles.action],identityText=sourceText[typedSourcePolicyFiles.identity],transformationText=sourceText[typedSourcePolicyFiles.transformation],coverageText=sourceText[typedSourcePolicyFiles.coverage];
  const common={
    metric_id:sourceReference(typedSourcePolicyFiles.indicator,uniqueSourceLine(indicatorText,'return Indicator{MetricID: observation.Dimension',typedSourcePolicyFiles.indicator),'MetricID','indicator_metric_id'),
    producer:sourceReference(typedSourcePolicyFiles.indicator,uniqueSourceLine(indicatorText,'producer := observation.Producer',typedSourcePolicyFiles.indicator),'Producer','indicator_producer'),
    action:sourceReference(typedSourcePolicyFiles.action,uniqueSourceLine(actionText,'return Action{IndicatorID: id, MetricID: candidate.indicator.MetricID',typedSourcePolicyFiles.action),'actionFor','action_copy'),
    indicatorHash:sourceReference(typedSourcePolicyFiles.identity,uniqueSourceLine(identityText,'func indicatorID(indicator sourcepolicy.Indicator) string',typedSourcePolicyFiles.identity),'indicatorID','full_indicator_hash'),
    transform:sourceReference(typedSourcePolicyFiles.transformation,uniqueSourceLine(transformationText,'left, right := make([]string, 0, len(ledger.Entries))',typedSourcePolicyFiles.transformation),'metricLedgerBound','full_indicator_multiset'),
    coverage:sourceReference(typedSourcePolicyFiles.coverage,uniqueSourceLine(coverageText,'return []ArtifactBinding{',typedSourcePolicyFiles.coverage),'CanonicalBindings','operation_keyed_coverage')
  };
  const coverageRows=coverageText.split(/\r?\n/).filter(line=>line.trim().startsWith('binding("')).length;
  if(coverageRows!==8)throw Error('Pinned artifact coverage binding count is not exactly 8');
  const records=typedSourcePolicySpecs.map(spec=>{
    const dimension=dimensionByConstant.get(spec.constant);
    const vocabularyLine=uniqueSourceLine(sourceText[typedSourcePolicyFiles.vocabulary],`${spec.constant} Dimension`,typedSourcePolicyFiles.vocabulary);
    const dispatchLine=uniqueSourceLine(dispatchText,spec.dispatch_anchor,typedSourcePolicyFiles.dispatch);
    const references=[sourceReference(typedSourcePolicyFiles.vocabulary,vocabularyLine,spec.constant,'source_policy_dimension'),sourceReference(typedSourcePolicyFiles.dispatch,dispatchLine,spec.constant,'source_policy_dispatch'),common.metric_id,common.producer,common.action,common.indicatorHash,common.transform,common.coverage];
    if(spec.helper_anchor)references.push(sourceReference(typedSourcePolicyFiles.dispatch,uniqueSourceLine(dispatchText,spec.helper_anchor,typedSourcePolicyFiles.dispatch),spec.helper_anchor.replace('func ','').replace('(','),'source_policy_helper'));
    return {schema:'gooo/typed-source-policy-lineage/v1',source_sha:sourceSHA,binding_scope:'EXACT_EXISTING_METRIC_ID_TYPED_SOURCE_RELATION_NOT_RUNTIME_EVIDENCE',metric_id:spec.metric_id,dimension_constant:spec.constant,dimension_literal:dimension.metric_id,meaning_ko:spec.meaning_ko,target_ko:spec.target_ko,subject_expression:spec.subject_expression??'observation.Subject',detail_expression:'observation.Detail',unit_ko:spec.unit_ko,observation_scope_ko:spec.scope_ko,policy_conditions:spec.conditions,comparison:spec.comparison,role:spec.role,producer:{expression:'observation.Producer',fallback:'meta-observer',fallback_limit:'빈 producer는 독립적인 원본 producer 증거가 아닙니다.',source:common.producer},consumer:spec.consumer,meta_operation:spec.operation,indicator_identity:{metric_id_expression:'observation.Dimension',fields:['MetricID','Family','Subject','SubjectKind','Value','Limit','Relation','Applicability','ApplicabilityRule','ApplicabilityReason','Blocking','Role','Proof','Producer','Consumer','Operation','Detail'],source:[common.metric_id]},action_identity:{fields:['IndicatorID','MetricID','Subject','SubjectKind','InputSubjectKind','InputContractSourceDigest','InputContractSemanticDigest','Applicability','ApplicabilityRule','ApplicabilityReason','Blocking','SourceIndicator','IndicatorOutcome','MetricProofChoice','MetricProducer','MetricConsumer','Operation','Activity','Output','IndependenceGroupID','ProofChoice','Executor','Evaluator','RequiredIndicatorIDs','ReceiptRequired','Priority'],source:[common.action]},full_indicator_identity:{formula:'sha256(json(Indicator))',source:[common.indicatorHash],note:'MetricID만이 아니라 full Indicator가 해시에 들어가므로 같은 MetricID의 subject/value/context가 서로 다른 IndicatorID를 만들 수 있습니다.'},source_metric_to_decision_ledger:{relation:'source metrics와 decision ledger의 full-indicator hash multiset 및 count를 정렬 비교합니다. native 실행·성공·권한 증거가 아닙니다.',source:[common.transform]},artifact_coverage_boundary:{count:coverageRows,keying:'operation/activity/evidence-key',metric_id_keyed:false,relation:'8개 operation/evidence-key binding은 MetricID별 source 또는 실행 증거로 승격하지 않습니다.',source:[common.coverage]},source_locations:references};
  });
  return {schema:'gooo/typed-source-policy-lineage-cohort/v1',source_sha:sourceSHA,dimension_count:records.length,source_files:Object.values(typedSourcePolicyFiles),artifact_coverage_binding_count:coverageRows,metric_ids:records.map(record=>record.metric_id),records,scope:'EXACT_19_SOURCE_POLICY_DIMENSIONS_ONLY_NOT_LANGUAGE_COMPLETENESS_OR_RUNTIME_EVIDENCE'};
}
const raw=await readFile(input,'utf8');
const atlas=JSON.parse(raw);
if(atlas.schema!=='gooo/source-metric-atlas/v1'||!Array.isArray(atlas.concepts)||!Array.isArray(atlas.obligations)||!Array.isArray(atlas.metrics))throw Error('Unsupported source catalog');
const typedSourcePolicy=await buildTypedSourcePolicy(sourceRoot,atlas.source_sha);
atlas.typed_source_policy_lineage=typedSourcePolicy;
const typedSourcePolicyByMetricID=new Map(typedSourcePolicy.records.map(record=>[record.metric_id,record]));
if(typedSourcePolicy.records.some(record=>!atlas.metrics.some(metric=>metric.id===record.metric_id)))throw Error('Typed source-policy ID is not an exact atlas metric membership');
for(const concept of atlas.concepts){concept.translation=concepts[concept.id]?{title:concepts[concept.id][0],description:concepts[concept.id][1],state:'EDITORIAL'}:{title:concept.id,description:'한국어 해설 미작성. 원문을 유지합니다.',state:'MISSING'};}
for(const concept of atlas.concepts){const n=narratives[concept.id];concept.narrative_ko=n?{problem:n[0],effect:n[1],state:'EDITORIAL_SOURCE_DECLARATION'}:null;for(const useCase of concept.use_cases){const translated=n?.[2][useCase.id];useCase.translation_ko=translated?{trigger:translated[0],expected:translated[1],state:'EDITORIAL_EXPECTATION_NOT_CURRENT_OBSERVATION'}:null;}}
const sourceCalls=atlas.source_contracts?.calls??[];
const sourceFieldVocabulary=observedFieldVocabulary(sourceCalls);
const releaseMetricContracts=atlas.release_metric_contracts?.contracts??[];
for(const metric of atlas.metrics)metric.release_metric_bindings=releaseMetricContracts.filter(contract=>contract.metric_id===metric.id);
const releaseMetricClassCounts=Object.fromEntries(['OUTCOME','DRIVER','GUARDRAIL'].map(className=>[className,releaseMetricContracts.filter(contract=>contract.class===className).length]));
const releaseMetricCohort={schema:'gooo/source-release-metric-cohort/v1',source_sha:atlas.release_metric_contracts?.source_sha??null,source_files:atlas.release_metric_contracts?.source_files??[],metric_count:atlas.release_metric_contracts?.metric_count??0,owner_count:atlas.release_metric_contracts?.owner_count??releaseMetricContracts.length,contract_count:releaseMetricContracts.length,complete_formula_count:releaseMetricContracts.filter(contract=>contract.formula_complete===true).length,unknown_count:atlas.release_metric_contracts?.unknowns?.length??0,class_counts:releaseMetricClassCounts,all_formula_fields_present:releaseMetricContracts.every(contract=>['actual','expected','comparator','unit','proof'].every(field=>contract.formula?.[field]?.expression&&contract.formula?.[field]?.reference?.path&&contract.formula?.[field]?.reference?.line>0)),scope:atlas.release_metric_contracts?.scope??'UNKNOWN'};
atlas.release_metric_cohort=releaseMetricCohort;
const releaseMetricSourceConcept=atlas.concepts.filter(concept=>concept.meta_operation===nativeEvidence.eligibility_receipt.meta_operation);
const releaseMetricValidation=validateReleaseMetricBindings(atlas,releaseMetricSourceConcept.length===1?releaseMetricSourceConcept[0].metric_bindings:[],nativeEvidence.source_head_sha);
atlas.release_metric_binding_validation=releaseMetricValidation;
const nativeBinding=bindNativeEvidence(atlas,nativeEvidence);
atlas.native_evidence={...nativeEvidence,binding:nativeBinding};
const guidedContract=call=>{const fieldGuides={arguments:annotateFields(call.argument_expressions,'argument'),results:annotateFields(call.result_field_expressions,'result')};for(const item of [...fieldGuides.arguments,...fieldGuides.results]){const source=(item.kind==='argument'?call.argument_expressions:call.result_field_expressions)?.[item.field];if(item.expression!==source)throw Error('Source field expression was not preserved for '+item.field)};return {...call,field_guides:fieldGuides}};
const sourceCallsByMetricID=new Map();
for(const call of sourceCalls){if(typeof call.metric_id!=='string'||!call.metric_id)throw Error('Resolved source contract has no exact metric ID');const calls=sourceCallsByMetricID.get(call.metric_id)??[];calls.push(call);sourceCallsByMetricID.set(call.metric_id,calls);}
for(const metric of atlas.metrics){const calls=(sourceCallsByMetricID.get(metric.id)??[]).map(guidedContract);metric.source_contracts=calls;metric.source_definition_binding=sourceDefinitionBinding(metric,calls);metric.typed_source_policy=typedSourcePolicyByMetricID.get(metric.id)??null;}
const partialContracts=atlas.source_contracts?.partial_calls??[];
const referenceKey=reference=>reference.path+'#'+reference.line+'#'+reference.kind;
const sortedReferences=references=>references.map(referenceKey).sort();
const partialReferenceMultiset=sortedReferences(partialContracts.map(record=>record.call));
const unresolvedReferenceMultiset=sortedReferences(atlas.source_contracts?.unresolved_calls??[]);
const sourceContractCohort={resolved_symbolic_calls:atlas.source_contracts?.calls?.length??0,unresolved_callsites:atlas.source_contracts?.unresolved_calls?.length??0,partial_contracts:partialContracts.length,recognized_constructor_callsites:(atlas.source_contracts?.calls?.length??0)+(atlas.source_contracts?.unresolved_calls?.length??0),partial_contracts_match_unresolved_calls:JSON.stringify(partialReferenceMultiset)===JSON.stringify(unresolvedReferenceMultiset),partial_reference_multiset_matches_unresolved_calls:JSON.stringify(partialReferenceMultiset)===JSON.stringify(unresolvedReferenceMultiset),partial_callsite_ids_unique:new Set(partialContracts.map(record=>record.callsite_id)).size===partialContracts.length};
atlas.partial_contracts=partialContracts;
atlas.source_contract_cohort=sourceContractCohort;
const exactSourceMetricIDs=[...sourceCallsByMetricID.keys()];
const sourceDefinitionBindingCohort={schema:'gooo/source-definition-binding-cohort/v1',join_rule:'metric.id === source_contract.metric_id',source_contract_property:'metric.source_contracts',metric_rows:atlas.metrics.length,source_call_count:sourceCalls.length,source_unique_metric_id_count:exactSourceMetricIDs.length,metric_rows_with_exact_source_contract:atlas.metrics.filter(metric=>metric.source_definition_binding.callsite_count>0).length,joined_source_call_count:atlas.metrics.reduce((sum,metric)=>sum+metric.source_definition_binding.callsite_count,0),joined_unique_metric_id_count:new Set(atlas.metrics.filter(metric=>metric.source_definition_binding.callsite_count>0).map(metric=>metric.id)).size,unjoined_source_call_count:sourceCalls.filter(call=>!new Set(atlas.metrics.map(metric=>metric.id)).has(call.metric_id)).length,multiple_callsite_metric_count:atlas.metrics.filter(metric=>metric.source_definition_binding.callsite_count>1).length,multiple_callsite_count:atlas.metrics.filter(metric=>metric.source_definition_binding.callsite_count>1).reduce((sum,metric)=>sum+metric.source_definition_binding.callsite_count,0),multiple_definition_metric_count:atlas.metrics.filter(metric=>metric.source_definition_binding.definition_count>1).length,multiple_definition_callsite_count:atlas.metrics.filter(metric=>metric.source_definition_binding.definition_count>1).reduce((sum,metric)=>sum+metric.source_definition_binding.callsite_count,0),partial_contracts_not_promoted:partialContracts.length,dynamic_prefix_not_promoted_count:atlas.metrics.filter(metric=>metric.source_definition_binding.state==='DYNAMIC_PREFIX_NOT_CONFIRMED').length,candidate_not_promoted_count:atlas.metrics.filter(metric=>metric.source_definition_binding.state==='CANDIDATE_ID_NOT_CONFIRMED').length,no_exact_source_contract_count:atlas.metrics.filter(metric=>metric.source_definition_binding.state==='NO_EXACT_SOURCE_CONTRACT').length,definition_grouping:'helper/signature/result shape; not semantic or runtime-value equivalence',scope:'Preserves existing exported source constructor definitions; not new definitions, runtime execution, usefulness, native evidence, or full-language completeness'};
atlas.source_definition_binding_cohort=sourceDefinitionBindingCohort;
atlas.source_field_vocabulary=sourceFieldVocabulary;
for(const metric of atlas.metrics){const translation=translateMetric(metric.id);metric.translation={...translation,traceability:(translation.source_backed||translation.untranslated_tokens.length)?metricTraceability(metric,translation):null};}
const untranslatedMetrics=atlas.metrics.filter(metric=>metric.translation.untranslated_tokens.length);
const untranslatedIDs=untranslatedMetrics.map(metric=>metric.id);
if(JSON.stringify(untranslatedIDs)!==JSON.stringify(untranslatedCohortIds))throw Error('Untranslated metric cohort changed; update the pinned source-backed cohort explicitly');
if(untranslatedIDs.some(id=>!metricTranslationCatalog[id]))throw Error('Untranslated metric cohort has no source-backed translation record');
const traceability=traceabilityRecords(untranslatedMetrics);
const traceabilityCounts=countTraceabilityClasses(traceability);
assertTraceabilityPartition();
if(traceability.length!==untranslatedMetrics.length||Object.values(traceabilityCounts).reduce((sum,count)=>sum+count,0)!==traceability.length)throw Error('Untranslated metric traceability population mismatch');
const sourceReferenceValidation=await validateSourceReferences(traceability,sourceRoot,atlas.source_sha);
if(sourceReferenceValidation.state!=='SOURCE_HEAD_VALIDATED')throw Error('Pinned source reference validation failed: '+JSON.stringify(sourceReferenceValidation));
atlas.metric_label_traceability=traceability;
atlas.metric_label_traceability_counts=traceabilityCounts;
const translationCohort={schema:'gooo/source-metric-atlas-translation-cohort/v1',total:untranslatedCohortIds.length,ids:untranslatedCohortIds,source_backed_count:sourceReferenceValidation.validated_records,source_reference_state:sourceReferenceValidation.state,source_reference_head:sourceReferenceValidation.source_head_sha,source_reference_validated_references:sourceReferenceValidation.validated_references,semantic_unknown_count:traceability.filter(record=>record.meaning_status?.endsWith('_UNKNOWN')).length,identifier_kind_counts:Object.fromEntries([...new Set(traceability.map(record=>record.identifier_kind))].sort().map(kind=>[kind,traceability.filter(record=>record.identifier_kind===kind).length])),classification_counts:traceabilityCounts,scope:'AUDIT_COHORT_NOT_COMPLETENESS_DENOMINATOR'};
atlas.metric_translation_cohort=translationCohort;
atlas.catalog_sha256=createHash('sha256').update(raw).digest('hex');
atlas.presentation_scope='REGISTRY_EXPORT_AND_LITERAL_INDEX_NOT_CURRENT_CONFORMANCE';
const json=JSON.stringify(atlas).replaceAll('<','\\u003c');
const html=await readFile(template,'utf8');
const marker='<script id="atlas-data" type="application/json">null</script>';
if(!html.includes(marker))throw Error('Atlas template marker absent');
await writeFile(output,html.replace(marker,()=>`<script id="atlas-data" type="application/json">${json}</script>`));
const partialStageCounts=Object.fromEntries([...new Set(partialContracts.map(record=>record.unknown?.stage??'UNKNOWN'))].sort().map(stage=>[stage,partialContracts.filter(record=>(record.unknown?.stage??'UNKNOWN')===stage).length]));
const report={schema:'gooo/source-metric-atlas-render-receipt/v2',source_sha:atlas.source_sha,concepts:atlas.concepts.length,obligations:atlas.obligations.length,assurance_obligations:atlas.assurance_obligations.length,metric_ids_and_candidates:atlas.metrics.length,lexical_activity_declarations:atlas.activities.length,scanned_files:atlas.scanned_sources.length,excluded_files:atlas.excluded_paths.length,source_contract_cohort:sourceContractCohort,source_definition_binding_cohort:sourceDefinitionBindingCohort,source_field_vocabulary:sourceFieldVocabulary,partial_contracts_by_stage:partialStageCounts,release_metric_cohort:releaseMetricCohort,release_metric_binding_validation:releaseMetricValidation,concept_translations_missing:atlas.concepts.filter(c=>c.translation.state==='MISSING').map(c=>c.id),metric_labels_with_untranslated_tokens:untranslatedIDs.length,metric_untranslated_ids:untranslatedIDs,metric_label_traceability_records:traceability,metric_label_traceability_counts:traceabilityCounts,metric_translation_cohort:translationCohort,source_reference_validation:sourceReferenceValidation,typed_source_policy:{schema:typedSourcePolicy.schema,source_sha:typedSourcePolicy.source_sha,dimension_count:typedSourcePolicy.dimension_count,artifact_coverage_binding_count:typedSourcePolicy.artifact_coverage_binding_count,metric_ids:typedSourcePolicy.metric_ids,scope:typedSourcePolicy.scope},native_evidence:{observation_state:nativeEvidence.observation_state,source_head_sha:nativeEvidence.source_head_sha,workflow_run_id:nativeEvidence.workflow.run_id,workflow_url:nativeEvidence.workflow.url,artifact_id:nativeEvidence.artifact.id,artifact_name:nativeEvidence.artifact.name,artifact_kind:nativeEvidence.artifact.kind,artifact_digest:nativeEvidence.artifact.digest,aggregate_report_artifact_id:nativeEvidence.aggregate_report_artifact.id,reported_decision:nativeEvidence.eligibility_receipt.reported_decision,map_decision:nativeEvidence.ingestion.state,ingestion_state:nativeEvidence.ingestion.state,ingestion_unknown:{stage:nativeEvidence.ingestion.stage,step:nativeEvidence.ingestion.step,reason:nativeEvidence.ingestion.reason,unknown_class:nativeEvidence.ingestion.unknown_class,next_operation:nativeEvidence.ingestion.next_operation,blocked_by:nativeEvidence.ingestion.blocked_by},platform_receipt_count:nativeEvidence.platform_receipts.length,denominators:{release_contract_cases:{value:nativeEvidence.denominator_observations.release_contract_cases.value,denominator:nativeEvidence.denominator_observations.release_contract_cases.denominator},meta_indicators:{value:nativeEvidence.denominator_observations.meta_indicators.value,denominator:nativeEvidence.denominator_observations.meta_indicators.denominator},release_eligibility_cells:{value:nativeEvidence.denominator_observations.release_eligibility_cells.value,denominator:nativeEvidence.denominator_observations.release_eligibility_cells.denominator}},binding:nativeBinding},current_conformance:'UNASSESSED'};
await writeFile(output+'.receipt.json',JSON.stringify(report,null,2)+'\n');
const narrativeCoverage={schema:'gooo/source-metric-atlas-translation-receipt/v2',source_sha:atlas.source_sha,concepts_total:atlas.concepts.length,concepts_translated:atlas.concepts.filter(c=>c.narrative_ko).length,usecases_total:atlas.concepts.reduce((n,c)=>n+c.use_cases.length,0),usecases_translated:atlas.concepts.reduce((n,c)=>n+c.use_cases.filter(u=>u.translation_ko).length,0),missing:atlas.concepts.flatMap(c=>[...(!c.narrative_ko?[c.id]:[]),...c.use_cases.filter(u=>!u.translation_ko).map(u=>c.id+'/'+u.id)]),metric_labels_with_untranslated_tokens:untranslatedIDs.length,metric_untranslated_ids:untranslatedIDs,metric_label_traceability_records:traceability,metric_label_traceability_counts:traceabilityCounts,metric_translation_cohort:translationCohort,scope:'EDITORIAL_TRANSLATION_COVERAGE_NOT_LANGUAGE_COMPLETION'};
await writeFile(output+'.translations.json',JSON.stringify(narrativeCoverage,null,2)+'\n');
if(process.env.GITHUB_STEP_SUMMARY)await writeFile(process.env.GITHUB_STEP_SUMMARY,'## Source metric atlas\n\n```json\n'+JSON.stringify(report,null,2)+'\n```\n');
console.log(JSON.stringify(report));
